# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfe2519fae240b72a2ae527038c7542f6bef314502828af684fe56be41273d9cfff0dcd33b3b0dd80e2c3ec86352f953264de8d4559bf74b2b3d13722125a1c1

test:
  secret_key_base: df0ce79ab8a3d00450aeba5e2e797531d98efcf6853f5b1220631c48eed7b03ae5024f4a3b2df7fd5558fa0e4923a2064c247bc99e7c4d433e3f1f7cfb84a47d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
